# Site
name: "Seneng Utami"
title: "Seneng Utami"
description: "I will take you on the fabulous world of exploration. Travel, culture, lifestyle. Eat, Pray, Love!"
logo: 'assets/images/logo4.png'
favicon: 'assets/images/logo4.png'
baseurl:
google_analytics: 'UA-112175180-1'
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: senengutami2@gmail.com

# Authors
authors:
  seneng:
    name: Seneng Utami
    display_name: seneng
    gravatar: 805dd03d474fb6e4f1284edf92e865e2
    email: senengutami2@gmail.com
    web: https://www.senengutami.net/
    description: "Writer at Migran Pos and a photographer by hobby."
    # twitter: https://twitter.com/wowthemesnet
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
# adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
